### ISSUE TITLE
PATH problem

### ISSUE THREAD

**Issue by ghost** [rtyler/gmrun#4]
i've tried to run 'PATH=$PATH:/myscriptfolder'; export PATH' in my terminal, but gmrun still does not recognize commands/scripts in this folder. I get: "ERROR: No such file".

I'm using debian testing, and xfce.

**Comment by rtyler** [comment]
This is because the `PATH` environment variable that `gmrun` uses is set by whatever terminal or session started the process. You cannot update the `PATH` for `gmrun` in the way you describe
